---
title: "Data download instructions"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F,message = F)
```

## Download data for this exercise in UFApps

  - Go to the landing page for UFApps (the page with all the app icons - in my web browser, the tab is called "Citrix Receiver")
- Launch the Google Chrome app
- Copy-paste this URL into Chrome and push enter: https://ndownloader.figshare.com/files/22775042 
- This will download a .zip file called "NEON-pheno-temp-timeseries_v2.zip". When the download completes, exit the Chrome app.
- Go back to the landing page and launch the M Drive app. 
- Open the Downloads folder.
- Select NEON-pheno-temp-timeseries_v2.zip. You may get a warning that opening files can be harmful to your computer; dismiss it.
- In the file explorer, select "Move to" and then "Choose location".
- In the window that pops up, navigate to `UFApps > Documents > EVS3000L > week6`. Select the `week6` folder and click Move.
- In the file explorer, navigate to `Documents > EVS3000L > week6`. 
- Select NEON-pheno-temp-timeseries_v2.zip. 
- At the top of the file explorer window, there's a pink button that says "Extract". Click on it.
- Click on "Extract all".
- Make sure the files will be extracted to the folder: `M:\Documents\EVS3000L\week6\NEON-pheno-temp-timeseries_v2` 
- Click Extract.
- Exit the M drive app. 